services:
    db:
        image: postgres:15
        container_name: mycontacts
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: mycontacts
        volumes:
            - pgdata:/var/lib/postgresql/data
            - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - mynetwork

volumes:
    pgdata: {}

networks:
    mynetwork:
